name: greet-time

on : [push]

jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
        - name: list file
          run: |
            pwd
            ls
        - name: simple js action
          id: greet
          uses: actions/hello-world-javascript-action@main
          with:
            who-to-greet: 'Mona the Octocat'
        - name: log greet time
          run: echo "${{steps.greet.outputs.time}}"
          