name: node-version-test

on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [8, 10, 12, 14]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            node-version: 10
            is_ubuntu_10: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 8
    runs-on: ${{matrix.os}}
    env: 
      IS_UBUNTU_10: ${{matrix.is_ubuntu_10}}
    steps:
      - name: log Node Version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: log Node Version
        run: |
          node -v
          echo $IS_UBUNTU_10




