name: node-version-test

on: push

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [8, 10, 12, 14]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: log Node Version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: log Node Version
        run: node -v




